export default {
  mode: 'move',
  tiles: [
    { id: 0, parent: null, ratio: 1, children: [6, 2], split: 'v' },
    { id: 1, parent: 6, ratio: 0.5 },
    { id: 2, parent: 0, ratio: 0.5, children: [20, 4], split: 'h' },
    { id: 3, parent: 24, ratio: 0.5 },
    { id: 4, parent: 2, ratio: 0.5 },
    { id: 6, split: 'h', ratio: 0.5, parent: 0, children: [1, 8] },
    { id: 5, ratio: 0.5, parent: 16 },
    { id: 8, split: 'v', ratio: 0.5, parent: 6, children: [16, 10] },
    { id: 7, ratio: 0.5, parent: 10 },
    { id: 10, split: 'h', ratio: 0.5, parent: 8, children: [7, 13] },
    { id: 13, ratio: 0.5, parent: 10 },
    { id: 16, split: 'h', ratio: 0.5, parent: 8, children: [5, 15] },
    { id: 15, ratio: 0.5, parent: 16 },
    { id: 20, split: 'v', ratio: 0.5, parent: 2, children: [24, 22] },
    { id: 19, ratio: 0.5, parent: 22 },
    { id: 22, split: 'h', ratio: 0.5, parent: 20, children: [19, 21] },
    { id: 21, ratio: 0.5, parent: 22 },
    { id: 24, split: 'h', ratio: 0.5, parent: 20, children: [3, 23] },
    { id: 23, ratio: 0.5, parent: 24 },
  ],
  move_options: null,
  move_options_dir: null,
  move_options_index: null,
  active: 13,
  show_tree: false,
  fill_types: ['stretch', 'contain', 'cover'],
  fill_type: 'stretch',
  print_preview: false,
  show_sidebar: true,
  control_dirs: 'arrows',
  km: {},
}
